'use strict';
/**
 * mcp-manager.js — MCP 服务器管理
 * 通过修改 DSH web profile 的 cordis.patch.yml 注入 dsh-mcp-client 插件实例。
 * 每个 MCP 服务器 = 一个 mcp-client loader entry。
 * 配置在 patch 文件里，需重启 DSH web (3080) 生效。
 */
const fs = require('fs');
const os = require('os');
const path = require('path');

const DSH_HOME = process.env.DSH_HOME || path.join(os.homedir(), '.dsh');
const PATCH_FILE = path.join(DSH_HOME, 'profiles', 'web', 'cordis.patch.yml');
const PLUGIN_NAME = 'mcp-client'; // cordis 插件注册名（非包名）
const ENTRY_PREFIX = 'mcp-server-';

/** 读取 patch 文件 —— 解析顶层 YAML 数组里的 loader entries */
function readPatch() {
  try {
    if (!fs.existsSync(PATCH_FILE)) return [];
    const raw = fs.readFileSync(PATCH_FILE, 'utf8');
    // 去掉注释行（#）和空行，解析 "- id: xxx" 的 entry 块
    const entries = [];
    const blocks = splitYamlEntries(raw);
    for (const block of blocks) {
      const entry = parseYamlEntry(block);
      if (entry) entries.push(entry);
    }
    return entries;
  } catch (e) {
    console.log('[mcp] 读取 patch 失败: ' + e.message);
    return [];
  }
}

/** 把 YAML 文本按顶层 "- " 条目切块（只有行首无缩进的 "- " 才是新 entry，数组元素 "- x" 有缩进不算） */
function splitYamlEntries(raw) {
  const lines = raw.split(/\r?\n/);
  const blocks = [];
  let cur = null;
  for (const line of lines) {
    if (!line.trim() || line.trim().startsWith('#')) continue;
    if (/^-\s/.test(line)) {
      // 行首（无前导空格）的 "- " → 新 entry
      if (cur !== null) blocks.push(cur);
      cur = [line];
    } else if (cur !== null) {
      cur.push(line);
    }
  }
  if (cur !== null) blocks.push(cur);
  return blocks;
}

/** 解析一个 YAML entry 块为 { id, name, config } */
function parseYamlEntry(lines) {
  const entry = { id: '', name: '', config: {} };
  let inConfig = false;
  let configKey = '';
  let containerKey = ''; // 嵌套对象容器（如 headers）
  const configDepth = -1;
  for (const line of lines) {
    const m = /^-\s*id:\s*"([^"]*)"/.exec(line);
    if (m) { entry.id = m[1]; continue; }
    const n = /^\s*name:\s*"?([^"\s]+)"?/.exec(line);
    if (n) { entry.name = n[1]; continue; }
    if (/^\s*config:\s*$/.test(line)) { inConfig = true; continue; }
    if (/^\s*config:\s*{/.test(line)) {
      // 单行 config: { ... }
      const json = line.replace(/^\s*config:\s*/, '').replace(/'/g, '"');
      try { entry.config = JSON.parse(json); } catch {}
      continue;
    }
    if (inConfig) {
      // 嵌套对象容器（headers: 后子键缩进更深）——先看是否是容器子键
      const isDeeper = /^\s{6,}[A-Za-z0-9_-]+\s*:/.test(line);
      if (isDeeper && containerKey && entry.config[containerKey] && typeof entry.config[containerKey] === 'object' && !Array.isArray(entry.config[containerKey])) {
        // headers: 下的子键 → 归入容器对象
        const km2 = /^\s*"?([A-Za-z0-9_-]+)"?\s*:\s*(.*)$/.exec(line.trim());
        if (km2) {
          entry.config[containerKey][km2[1]] = km2[2].trim() === '' ? '' : unquote(km2[2]);
          continue;
        }
      }
      const km = /^\s*"?([A-Za-z0-9_]+)"?\s*:\s*(.*)$/.exec(line);
      if (km) {
        configKey = km[1];
        // 数组容器（args: / env: 后无值）→ 初始化为数组；对象容器（headers:）→ 初始化为对象；普通值 → 存字符串
        if (km[2].trim() === '') {
          if (configKey === 'headers' || configKey === 'env') {
            entry.config[configKey] = {};
            containerKey = configKey;
          } else {
            entry.config[configKey] = [];
            containerKey = '';
          }
        } else {
          entry.config[configKey] = unquote(km[2]);
          containerKey = '';
        }
      } else if (configKey && Array.isArray(entry.config[configKey]) && /^\s*-\s*(.+)$/.test(line)) {
        // 数组元素（args/env 列表）
        const vm = /^\s*-\s*(.+)$/.exec(line);
        entry.config[configKey].push(unquote(vm[1]));
      }
    }
  }
  if (!entry.id || !entry.name) return null;
  return entry;
}

function unquote(v) {
  const s = v.trim();
  if (s.startsWith('"') && s.endsWith('"')) return s.slice(1, -1);
  if (s.startsWith("'") && s.endsWith("'")) return s.slice(1, -1);
  return s;
}

/** 把 entries 序列化为 YAML（保持简单结构）——注释保持 ASCII（避免 DSH 规范化出现编码问题） */
function writePatch(entries) {
  const header = `# dsh profile patch layer for MCP servers (generated by DSH Desktop MCP manager)
# One entry = one dsh-mcp-client plugin instance (one MCP server).
`;
  const lines = [header];
  for (const e of entries) {
    lines.push(`- id: "${e.id}"`);
    lines.push(`  name: "${e.name}"`);
    if (e.config && Object.keys(e.config).length) {
      lines.push('  config:');
      for (const [k, v] of Object.entries(e.config)) {
        if (Array.isArray(v)) {
          lines.push(`    ${k}:`);
          for (const item of v) lines.push(`      - "${item}"`);
        } else if (typeof v === 'string') {
          lines.push(`    ${k}: "${v}"`);
        } else if (typeof v === 'boolean') {
          lines.push(`    ${k}: ${v}`);
        } else if (typeof v === 'number') {
          lines.push(`    ${k}: ${v}`);
        } else if (v && typeof v === 'object') {
          lines.push(`    ${k}:`);
          for (const [k2, v2] of Object.entries(v)) {
            if (typeof v2 === 'string') lines.push(`      ${k2}: "${v2}"`);
            else lines.push(`      ${k2}: ${v2}`);
          }
        }
      }
    }
  }
  try {
    fs.mkdirSync(path.dirname(PATCH_FILE), { recursive: true });
    fs.writeFileSync(PATCH_FILE, lines.join('\n') + '\n', 'utf8');
    return true;
  } catch (e) {
    console.log('[mcp] 写入 patch 失败: ' + e.message);
    return false;
  }
}

/** 列出已配置的 MCP 服务器 */
function listMcpServers() {
  return readPatch()
    .filter((e) => e.name === PLUGIN_NAME || e.name.includes('mcp-client'))
    .map((e) => ({
      id: e.id,
      serverName: e.config?.serverName || e.id.replace(ENTRY_PREFIX, ''),
      transport: e.config?.transport || 'stdio',
      command: e.config?.command || '',
      args: e.config?.args || [],
      url: e.config?.url || '',
      headers: e.config?.headers || {},
      cwd: e.config?.cwd || '',
      toolCallTimeoutMs: e.config?.toolCallTimeoutMs || 300000,
      failOnStartupError: !!e.config?.failOnStartupError,
      enabled: !e.config?.disabled,
    }));
}

/** 添加一个 MCP 服务器 */
function addMcpServer(spec) {
  const entries = readPatch();
  const serverName = (spec.serverName || '').trim();
  const id = ENTRY_PREFIX + (serverName || 'server-' + Date.now());
  if (entries.some((e) => e.id === id)) {
    return { ok: false, error: `服务器 ${serverName} 已存在` };
  }
  const config = {
    transport: spec.transport === 'http' || spec.transport === 'streamable-http' ? 'streamable-http' : 'stdio',
    serverName,
    ...(spec.transport === 'http' || spec.transport === 'streamable-http'
      ? { url: spec.url || '', headers: spec.headers || {} }
      : { command: spec.command || 'npx', args: spec.args || [], cwd: spec.cwd || '' }),
    toolCallTimeoutMs: spec.toolCallTimeoutMs || 300000,
    failOnStartupError: !!spec.failOnStartupError,
  };
  entries.push({ id, name: PLUGIN_NAME, config });
  const ok = writePatch(entries);
  return ok ? { ok: true, id } : { ok: false, error: '写入配置失败' };
}

/** 删除 MCP 服务器 */
function removeMcpServer(id) {
  let entries = readPatch();
  const before = entries.length;
  entries = entries.filter((e) => e.id !== id);
  if (entries.length === before) return { ok: false, error: '未找到 ' + id };
  const ok = writePatch(entries);
  return ok ? { ok: true } : { ok: false, error: '写入配置失败' };
}

/** 启用/停用 */
function toggleMcpServer(id, enabled) {
  const entries = readPatch();
  const e = entries.find((x) => x.id === id);
  if (!e) return { ok: false, error: '未找到 ' + id };
  if (enabled) delete e.config.disabled;
  else e.config.disabled = true;
  const ok = writePatch(entries);
  return ok ? { ok: true } : { ok: false, error: '写入配置失败' };
}

/** GitHub 热门 MCP 推荐（按 star 搜索 topic:mcp 仓库，实时，无固定列表） */
async function fetchMcpRecommendations(limit = 20) {
  const https = require('https');
  const token = process.env.DSH_GITHUB_TOKEN || '';
  const q = 'topic:mcp server in:name,description';
  const url = `https://api.github.com/search/repositories?q=${encodeURIComponent(q)}&sort=stars&order=desc&per_page=${limit}`;
  return new Promise((resolve) => {
    const req = https.get(url, {
      headers: {
        'User-Agent': 'dsh-desktop',
        Accept: 'application/vnd.github+json',
        ...(token ? { Authorization: 'Bearer ' + token } : {}),
      },
      timeout: 5000,
    }, (res) => {
      let d = '';
      res.on('data', (c) => (d += c));
      res.on('end', () => {
        if (res.statusCode !== 200) return resolve([]);
        try {
          const j = JSON.parse(d);
          const items = (j.items || []).map((it) => ({
            fullName: it.full_name,
            name: it.name,
            stars: it.stargazers_count,
            description: (it.description || '').slice(0, 140),
            htmlUrl: it.html_url,
            defaultBranch: it.default_branch || 'main',
            topics: it.topics || [],
          }));
          resolve(items);
        } catch { resolve([]); }
      });
    });
    req.on('error', () => resolve([]));
    req.on('timeout', () => { req.destroy(); resolve([]); });
  });
}

module.exports = {
  listMcpServers,
  addMcpServer,
  removeMcpServer,
  toggleMcpServer,
  fetchMcpRecommendations,
  getPatchFile: () => PATCH_FILE,
};